// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe061N8FR8exVsfmhZtxGzfneLYr2lcHk',
    appId: '1:984571930732:web:2dc7d9877c80a7d731d049',
    messagingSenderId: '984571930732',
    projectId: 'e-commrace-app-830af',
    authDomain: 'e-commrace-app-830af.firebaseapp.com',
    storageBucket: 'e-commrace-app-830af.appspot.com',
    measurementId: 'G-BZL56VMN5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVnNWv3q9lln_SASCklslBigQaPVTSYls',
    appId: '1:984571930732:android:51e3a188792fe6c631d049',
    messagingSenderId: '984571930732',
    projectId: 'e-commrace-app-830af',
    storageBucket: 'e-commrace-app-830af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUEspmr1o44XrcC4YCHp8pmDtuVVFmm-M',
    appId: '1:984571930732:ios:d55552d7a9bc17af31d049',
    messagingSenderId: '984571930732',
    projectId: 'e-commrace-app-830af',
    storageBucket: 'e-commrace-app-830af.appspot.com',
    androidClientId: '984571930732-si0bqj4qsdohtd25ht7eo5ecublop56j.apps.googleusercontent.com',
    iosClientId: '984571930732-7503lpgd6k1vd20biin4ulpm14qri783.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe061N8FR8exVsfmhZtxGzfneLYr2lcHk',
    appId: '1:984571930732:web:bf27456617b164c231d049',
    messagingSenderId: '984571930732',
    projectId: 'e-commrace-app-830af',
    authDomain: 'e-commrace-app-830af.firebaseapp.com',
    storageBucket: 'e-commrace-app-830af.appspot.com',
    measurementId: 'G-RXEDFXJ31S',
  );
}
